### ISSUE TITLE
Missing json files in published package

### ISSUE THREAD

**Issue by PatrikTheDev** [randombk/chatterbox-vllm#12]
Hello, when I install this package in a different repo via uv, the json config files from /src/chatterbox-vllm/models are missing which causes runtime issues.

I've temporarily hooked up a script to place them there manually but the distributed package should contain them. Could you please take a look at it?

**Comment by randombk** [comment]
This should fix it, but let me know if the issue continues

**Comment by PatrikTheDev** [comment]
As far as I'm able to tell, the issue still happens, when installing the latest version of the package (even by specifying the repository as the source), the tokenizer.json file is missing

<img width="265" height="607" alt="Image" src="https://github.com/user-attachments/assets/4138ccfe-e8cf-4033-abf6-b956c9213ed4" />

if I clone the repository, the file is present: 

<img width="265" height="365" alt="Image" src="https://github.com/user-attachments/assets/b95bec5e-47e6-45b0-b4ca-7e34f286f715" />

I feel like the issue is in the publishing process of the package or how uv/pip handle packages. Can you please reopen this issue?

**Comment by randombk** [comment]
This should now be fixed. Please reopen if issues continue to occur
